[tool.poetry]
name = "channel-copilot"
version = "0.1.0"
description = ""
authors = ["Nicolas Molina Monroy <hi@nicobytes.com>"]
readme = "README.md"
packages = [{include = "channel_copilot"}]

[tool.poetry.dependencies]
python = "^3.10"
langchain = "^0.0.270"
openai = "^0.27.8"
openai-whisper = "^20230314"
python-dotenv = "^1.0.0"
pydantic = "^1.10.9"
ffmpeg-python = "^0.2.0"
moviepy = "^1.0.3"
typer = "^0.9.0"
rich = "^13.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
